apiVersion: apps/v1
kind: Deployment
metadata:
 name: vt-deployment
spec:
 replicas: 5
 selector:
  matchLabels:
   tier: frontend
 template:
  metadata:
   labels:
    tier: frontend
  spec:
   containers:
   - name: php-redis
     image: gcr.io/google_samples/gb-frontend:v6