apiVersion: v1
kind: Pod
metadata:
 name: configmap-pod
spec:
 containers:
 - image: nginx
   name: configmap-pod
   volumeMounts:
   - name: config-volume
     mountPath: "etc/config"
 volumes:
 - name: config-volume
   configMap:
    name: dev-properties
 restartPolicy: Never