apiVersion: v1
kind: Pod
metadata:
 name: secretmount
spec:
 containers:
 - image: nginx
   name: secretmount
   volumeMounts:
   - name: foo
     mountPath: "etc/foo"
 volumes:
 - name: foo
   secret:
    secretName: firstsecret