apiVersion: v1
kind: Pod
metadata:
 name: secret-pod
spec:
 containers:
 - image: nginx
   name: secretmount
   volumeMounts:
   - name: foo
     mountPath: "etc/secret"
 volumes:
 - name: foo
   secret:
    secretName: app-creds

